RESULTING_HANDS = {
  royal_flush: [
    Card.new("10", "spades", 9),
    Card.new("J", "spades", 10),
    Card.new("Q", "spades", 11),
    Card.new("K", "spades", 12),
    Card.new("A", "spades", 13),
  ],
  straight_flush: [
    Card.new("2", "spades", 1),
    Card.new("3", "spades", 2),
    Card.new("4", "spades", 3),
    Card.new("5", "spades", 4),
    Card.new("6", "spades", 5),
  ],
  poker: [
    Card.new("A", "spades", 13),
    Card.new("A", "hears", 13),
    Card.new("9", "spades", 8),
    Card.new("A", "diamonds", 13),
    Card.new("A", "clover", 13),
  ],
  full_house: [
    Card.new("A", "spades", 13),
    Card.new("A", "hears", 13),
    Card.new("9", "spades", 8),
    Card.new("9", "diamonds", 8),
    Card.new("A", "clover", 13),
  ],
  flush: [
    Card.new("A", "spades", 13),
    Card.new("4", "spades", 3),
    Card.new("6", "spades", 5),
    Card.new("K", "spades", 12),
    Card.new("J", "spades", 10),
  ],
  straight: [
    Card.new("2", "spades", 1),
    Card.new("3", "clover", 2),
    Card.new("4", "spades", 3),
    Card.new("5", "hearts", 4),
    Card.new("6", "spades", 5),
  ],
  three_of_aces: [
    Card.new("A", "spades", 13),
    Card.new("A", "hears", 13),
    Card.new("9", "spades", 8),
    Card.new("2", "diamonds", 1),
    Card.new("A", "clover", 13),
  ],
  three_of_nines: [
    Card.new("9", "spades", 8),
    Card.new("A", "hears", 13),
    Card.new("9", "spades", 8),
    Card.new("2", "diamonds", 1),
    Card.new("9", "clover", 8),
  ],
  two_pairs: [
    Card.new("A", "spades", 13),
    Card.new("A", "hears", 13),
    Card.new("3", "spades", 2),
    Card.new("2", "diamonds", 1),
    Card.new("3", "clover", 2),
  ],
  pair: [
    Card.new("A", "spades", 13),
    Card.new("A", "hears", 13),
    Card.new("3", "spades", 2),
    Card.new("2", "diamonds", 1),
    Card.new("4", "clover", 3),
  ],
  high_card_ace: [
    Card.new("A", "spades", 13),
    Card.new("J", "hears", 10),
    Card.new("3", "spades", 2),
    Card.new("2", "diamonds", 1),
    Card.new("4", "clover", 3),
  ],
  high_card_J: [
    Card.new("5", "spades", 4),
    Card.new("J", "hears", 10),
    Card.new("3", "spades", 2),
    Card.new("2", "diamonds", 1),
    Card.new("4", "clover", 3),
  ],
}
